site_name: NOVA Docs
theme:
  name: mkdocs
  custom_dir: theme
repo_url: https://github.com/NOVA-Team/docs/
site_url: https://novaapi.net/docs/
strict: true

copyright: Copyright © 2015 The NOVA team. NOVA is licensed under LGPLv3 - <a href="mailto:info@novaapi.net">info@novaapi.net</a>

markdown_extensions:
  - smarty
# - urlize
  - tables
  - fenced_code

nav:
  - .hidden:
    - Home: index.md
  - Mod Development:
    - Getting started: Mod Development/Getting Started.md
    - NOVA Gradle: Mod Development/NOVA Gradle.md
    - Blocks: Mod Development/Blocks.md
    - Items: Mod Development/Items.md
    - Events: Mod Development/Events.md
  - NOVA Development:
    - Development Workspace Setup: NOVA Development/Development Workspace Setup.md
    - Formatting: NOVA Development/Formatting.md
    - JavaDoc Style: NOVA Development/JavaDoc Style.md
