site_name: NOVA Docs
theme_dir: theme
repo_url: https://github.com/NOVAAPI/docs/
strict: true
markdown_extensions:
  - smarty
  - urlize
  - tables
  - fenced_code

pages:
  - HOME: 'index.md'
  - MOD DEVELOPMENT:
    - 'Getting started': 'Mod Development/Getting Started.md'
    - 'Blocks': 'Mod Development/Blocks.md'
    - 'Events': 'Mod Development/Events.md'
  - NOVA DEVELOPMENT:
    - 'Development Workspace Setup': 'NOVA Development/Development Workspace Setup.md'
    - 'Formatting': 'NOVA Development/Formatting.md'
    - 'JavaDoc Style': 'NOVA Development/JavaDoc Style.md'
