site_name: NOVA Docs
theme:
  name: mkdocs
  custom_dir: theme
repo_url: https://github.com/NOVA-Team/docs/
strict: true

markdown_extensions:
  - smarty
  - urlize
  - tables
  - fenced_code

pages:
  - Home: index.md
  - Mod Development:
    - Getting started: Mod Development/Getting Started.md
    - NOVA Gradle: Mod Development/NOVA Gradle.md
    - Blocks: Mod Development/Blocks.md
    - Items: Mod Development/Items.md
    - Events: Mod Development/Events.md
  - NOVA Development:
    - Development Workspace Setup: NOVA Development/Development Workspace Setup.md
    - Formatting: NOVA Development/Formatting.md
    - JavaDoc Style: NOVA Development/JavaDoc Style.md
